services:
  video_feed_app:
    container_name: video_feed_app        
    image: "ghcr.io/huzaifairfan/video_feed_app:0.1"
    restart: unless-stopped
    
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - DATABASE=video_feed_crawler
      - ADMIN_PASSWORD=aa

    ports:
      - '3000:3000' 

    command: npm run start -- -H 0.0.0.0 -p 3000


    depends_on:
      - mongodb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`dev.huzaifairfan.com`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=le"
    networks:
      - video_feed
      - web


  mongodb:
    container_name: mongodb
    image: mongo:8-noble
    restart: unless-stopped

    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
    networks:
      - video_feed
      
  video_feed_crawler:
    container_name: video_feed_crawler        
    image: "ghcr.io/huzaifairfan/video_feed_crawler:0.1"
    restart: unless-stopped

    environment:
      - UV_LINK_MODE=copy
      - SELENIUM_URL=http://selenium_chrome:4444/wd/hub
      - MONGODB_URI=mongodb://mongodb:27017/
      - DATABASE=video_feed_crawler
      - CELERY_BROKER_URL=redis://redis:6379/0
      
    command: >
      sh -c "celery -A celery_app beat --loglevel=info & 
             celery -A celery_app worker --loglevel=info"
    depends_on:
      - selenium_chrome
      - mongodb
      - redis
    networks:
      - video_feed
  selenium_chrome:
    container_name: selenium_chrome
    image: selenium/standalone-chrome:130.0-chromedriver-130.0-20250414
    restart: unless-stopped

    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: "2g"
    networks:
      - video_feed

  redis:
    container_name: redis
    image: redis:7.4-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server
    volumes: 
      - redis:/data
    networks:
      - video_feed


volumes:
  redis:
    driver: local
  mongodb:
    driver: local



networks:
  video_feed:
    driver: bridge
  web:
    external: true